# May be overwritten in .github/workflows/github-pages.yml or other config files
baseURL = 'https://uc2025.qgis.org/'
languageCode = 'en-us'
title = 'QGIS UC Website'
theme = 'hugo-bulma-blocks-theme'
# Default pagination.
# Can override this when needed e.g. {{ range (.Paginator 5).Pages }}
[pagination]
  paginate = 50

# See https://mertbakir.gitlab.io/hugo/syntax-highlighting-in-hugo/
pygmentsUseClasses = true
pygmentsCodefences = true


# Folders in these folders get published automatically
staticDir = ['static']

# See https://gohugo.io/templates/robots/
# Set it to false to create a robots.txt file without using a template.
# The file robot.txt will be copied into the root folder when building
# the static file
enableRobotsTXT = false

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
  # See readme for submenu notes
  submenu = 'submenus'

[params]
# Min hugo version
minHugoVersion = "0.139.0"
# Brand colours:
primary1 = "#589632"
primary2 = "#55828b"
primary3 = "#395c6b"
primary4 = "#EEE766"
primary5 = "#93B023"
primary6 = "#ee7913"
primary1-invert = "#fff"
primary2-invert = "#eeeeee"
primary3-invert = "#eeeeee"
primary4-invert = "#363636"
primary5-invert = "#eeeeee"
primary6-invert = "#fff"
links = "#3A9800"
# TODO update these to gradient colours like above
complementary1 = "#93B023"
complementary2 = "#ee7913"
complementary3 = "#EEE766"
complementary4 = "#93b023"
complementary5 = "#a7cecb"
complementary6 = "#589732"
complementary7 = "#93B022"
complementary8 = "#385C6B"
light1 = "#fbfbfb"
light2 = "#eeeeee"
light3 = "#E7E7E7"
dark1 = "#808080"
dark2 = "#000"
text-primary1 = "#002033"
text-primary2 = "#4D6370"
# Bulma specific colours based on our branding
black = "#000"
white = "#ffffff"
grey-dark = "#444444"
grey-darker = "#363636"
grey-light = "#d4d4d4"
primary = "#a7cecb"
danger = "#ee7913"
info = "#93b023"
success = "#589632"
warning = "#EEE766"
link = "#ee7913"
# Brand fonts to override bulma font families
heading-font = "'Twemoji Country Flags', 'Trueno', sans-serif"
text-font = "'Twemoji Country Flags', 'Trueno', sans-serif"
fancy-font = "'Sevillana', cursive"

menuFontClass = "is-size-6"
## Gh repo for site footer (include trailing slash)
githubUrl = "https://github.com/kartoza/hugo-bulma-blocks-theme/"
## GH Repo for filing a new issue
githubIssueUrl = "https://github.com/kartoza/hugo-bulma-blocks-theme/issues/new/choose"
### Edit content repo (set to automatically enter "edit" mode; this is good for "improve this page" links)
githubEditUrl = "https://github.com/kartoza/hugo-bulma-blocks-theme/edit/main"
### Radius for boxes
corner-radius = "0px"

## Url to navigation web component
uniNavHeaderUrl = 'https://qgis.github.io/qgis-uni-navigation/index.js'
uniNavHeaderLocationPrefix = ""

## Url to news feed. After URL change you have to check 
## themes/hugo-bulma-blocks-theme/layouts/partials/contextmenu.html 
## file to ensure that it adresses the correct keys 
newsfeed ='https://feed.qgis.org/?lang=en&json=1'

## This will turn on Coockie popup. True to show popup
cookiesstate = false

# Matomo
matomoURL = "//matomo.qgis.org/"
matomoSiteId = '7'

# commit hash file
commitFile = "config/commit.toml"

# This will cause html in markdown files to be rendered directly
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Syntax highlighter for code blocks
# See https://mertbakir.gitlab.io/hugo/syntax-highlighting-in-hugo/
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false
      style = "monokai"
    
[markup.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 2


sectionPagesMenu = 'main'
# See https://gohugo.io/content-management/menus/
[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  name = "Schedule"
  url = "/schedule/"
  weight = 30

[[menu.main]]
  name = "Schedule"
  parent = "Detailed Schedule"
  url = "/schedule-details/"
  weight = 10

[[menu.main]]
  name = "Sponsors"
  url = "/sponsors/"
  weight = 40

[[menu.main]]
  name = "Attending"
  url = "/attending/"
  weight = 50

[[menu.main]]
  name = "Tickets"
  url = "/tickets/"
  weight = 60

[outputs]
  home = ["HTML", "RSS", "JSON"]


